version: 2
jobs:
  build:
    docker:
      - image: golang
    environment:
      GO111MODULE: "on"
    working_directory: /go/src/github.com/raviqqe/gherkin2markdown
    steps:
      - checkout

      - run:
          name: Dependencies
          command: |
            go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
            go get -d -t ./...

      - run:
          name: Lint
          command: golangci-lint run

      - run:
          name: Build
          command: go build

      - run:
          name: Test
          command: go test -covermode atomic -coverprofile coverage.txt

      - run:
          name: Coverage Report
          command: curl -s https://codecov.io/bash | bash
